# Generated by Django 4.1 on 2024-06-07 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mwst", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="userId",
            new_name="userid",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="userName",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="userinfo",
            old_name="userPwd",
            new_name="userpwd",
        ),
    ]
